### ISSUE TITLE
How to set properties on created entities?

### ISSUE THREAD

**Issue by TheEnjinia** [MaltegoTech/maltego-trx#47]
Maybe this is obvious, but I am not seeing a way in the documentation and in the examples to set the properties of an entity. 
For example setting the value for the Person entity, the "Value" property can be manipulated, which is apparently the "Full Name" property, but to me there is no apparent way to manipulate "Surname" and "First Names"

How can this be achieved?

**Comment by tendai-zw** [comment]
You can do it as follows:

``` Python 
    person_entity = MaltegoEntity(type="maltego.Person", value="John Doe")`
    person_entity.addProperty(fieldName="other_name", displayName="Other Name", matchingRule="loose", value="XYZ Name")
     person_entity.addProperty(fieldName="first_names", displayName="First Names", matchingRule="loose", value="John GI")
     person_entity.addProperty(fieldName="surname", displayName="Surname", matchingRule="loose", value="Joe")
```
the code reference is here - https://github.com/MaltegoTech/maltego-trx/blob/b0c3eae5f304a1c16a68aa1d3406981ac373420d/maltego_trx/maltego.py#L88 

You can refer to example Transforms here:

-  https://github.com/MaltegoTech/maltego-ltc/tree/main/modules 

- https://github.com/MaltegoTech/greynoise-maltego/blob/20afc6e45ce48ed0f3b9a4533831c50b1b59c258/transforms/GreyNoiseCommunityIPLookup.py#L81
